name: new_chatgpt
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  animated_text_kit: ^4.2.2
  appinio_social_share: ^0.3.2
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  http: ^1.3.0
  image_cropper: ^8.1.0
  image_picker: ^1.1.2
  loading_animation_widget: ^1.3.0
  onesignal_flutter: ^5.2.9
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
