// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4avbA9oQJ3iSQO1hvvFbF38NmVpIk42M',
    appId: '1:872889034627:web:b24e87098c8705da7e78b6',
    messagingSenderId: '872889034627',
    projectId: 'chatgpt-workspace',
    authDomain: 'chatgpt-workspace.firebaseapp.com',
    storageBucket: 'chatgpt-workspace.firebasestorage.app',
    measurementId: 'G-STK5D48YR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5MFZicFC7CHYyEWVUdHThFn_Ax-NH7WI',
    appId: '1:872889034627:android:ac5e77d851bad5587e78b6',
    messagingSenderId: '872889034627',
    projectId: 'chatgpt-workspace',
    storageBucket: 'chatgpt-workspace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-x8-3NRo8aJqpKwTk_tw7Lx_l2NP1FcM',
    appId: '1:872889034627:ios:0ccf35eb18fc90757e78b6',
    messagingSenderId: '872889034627',
    projectId: 'chatgpt-workspace',
    storageBucket: 'chatgpt-workspace.firebasestorage.app',
    iosBundleId: 'com.example.newChatgpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-x8-3NRo8aJqpKwTk_tw7Lx_l2NP1FcM',
    appId: '1:872889034627:ios:0ccf35eb18fc90757e78b6',
    messagingSenderId: '872889034627',
    projectId: 'chatgpt-workspace',
    storageBucket: 'chatgpt-workspace.firebasestorage.app',
    iosBundleId: 'com.example.newChatgpt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4avbA9oQJ3iSQO1hvvFbF38NmVpIk42M',
    appId: '1:872889034627:web:9763c11434ce1b2b7e78b6',
    messagingSenderId: '872889034627',
    projectId: 'chatgpt-workspace',
    authDomain: 'chatgpt-workspace.firebaseapp.com',
    storageBucket: 'chatgpt-workspace.firebasestorage.app',
    measurementId: 'G-ZELXT0863Q',
  );
}
